//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InternetBanking
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransaccione
    {
        public int Id { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public string Monto { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    }
}
